# Generated by Django 2.0.1 on 2019-07-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YGEat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eat_img', models.CharField(max_length=256, verbose_name='图片')),
                ('eat_content', models.CharField(max_length=200, verbose_name='描述')),
                ('eat_time', models.CharField(max_length=50, verbose_name='时间')),
            ],
            options={
                'verbose_name': '吃喝玩乐',
                'verbose_name_plural': '吃喝玩乐',
                'db_table': 'ygeat',
            },
        ),
    ]
