# Generated by Django 2.0.1 on 2019-07-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YGUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_phone', models.CharField(max_length=30, null=True, verbose_name='手机号码')),
                ('nickname', models.CharField(max_length=20, null=True, verbose_name='昵称')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10, null=True, verbose_name='性别')),
                ('u_auth_string', models.CharField(max_length=256, null=True, verbose_name='用户密码')),
                ('idcard', models.CharField(max_length=20, null=True, verbose_name='身份证')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d', verbose_name='用户图像')),
                ('balance', models.FloatField(default=0.0, null=True, verbose_name='账户余额')),
                ('u_level', models.CharField(choices=[('0', '大众会员'), ('1', '白银会员'), ('2', '黄金会员'), ('3', '钻石会员')], default=0, max_length=20, null=True, verbose_name='用户等级')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'users',
            },
        ),
    ]
