# Generated by Django 2.0.1 on 2019-07-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField(verbose_name='城市ID')),
                ('name', models.CharField(max_length=20, verbose_name='城市名称')),
                ('ishot', models.IntegerField(choices=[(0, '非热门城市'), (1, '热门城市')], default=0, verbose_name='是否热门')),
                ('py_name', models.CharField(max_length=50, verbose_name='拼音名称')),
            ],
            options={
                'verbose_name': '全国各大城市',
                'verbose_name_plural': '全国各大城市',
                'db_table': 'places',
            },
        ),
        migrations.CreateModel(
            name='YGChosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=2000, verbose_name='图片')),
                ('name', models.CharField(max_length=100, verbose_name='图片名称')),
                ('trackid', models.IntegerField(verbose_name='图片ID')),
            ],
            options={
                'verbose_name': '精选推荐',
                'verbose_name_plural': '精选推荐',
                'db_table': 'chosen',
            },
        ),
        migrations.CreateModel(
            name='YGNav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=2000, verbose_name='图片')),
                ('name', models.CharField(max_length=100, verbose_name='图片名称')),
                ('trackid', models.IntegerField(verbose_name='图片ID')),
            ],
            options={
                'verbose_name': '导航',
                'verbose_name_plural': '导航',
                'db_table': 'nav',
            },
        ),
        migrations.CreateModel(
            name='YGNavDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=2000, verbose_name='图片')),
                ('name', models.CharField(max_length=100, verbose_name='图片名称')),
                ('trackid', models.IntegerField(verbose_name='图片ID')),
                ('yg_productid', models.IntegerField()),
            ],
            options={
                'verbose_name': '导航详情',
                'verbose_name_plural': '导航详情',
                'db_table': 'details',
            },
        ),
        migrations.CreateModel(
            name='YGWheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=2000, verbose_name='图片')),
                ('name', models.CharField(max_length=100, verbose_name='图片名称')),
                ('trackid', models.IntegerField(verbose_name='图片ID')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'wheel',
            },
        ),
    ]
