# Generated by Django 2.0.1 on 2019-06-26 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YGAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yg_addr', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'ygaddress',
            },
        ),
        migrations.CreateModel(
            name='YGCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_goods_num', models.IntegerField(default=1)),
                ('c_is_select', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ygcart',
            },
        ),
        migrations.CreateModel(
            name='YGChosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('trackid', models.IntegerField()),
            ],
            options={
                'db_table': 'ygchosen',
            },
        ),
        migrations.CreateModel(
            name='YGComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yg_comments', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='YGGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ygg_goodsid', models.IntegerField()),
                ('ygg_goods_wheel_img', models.CharField(max_length=255)),
                ('ygg_goodsname', models.CharField(max_length=50)),
                ('ygg_goods_desc', models.CharField(max_length=100)),
                ('ygg_price', models.FloatField()),
                ('ygg_marketprice', models.FloatField()),
                ('ygg_goods_groupid', models.CharField(max_length=20)),
                ('ygg_goods_childcid', models.CharField(max_length=20)),
                ('ygg_detail_img', models.CharField(max_length=1000)),
                ('ygg_stock', models.IntegerField()),
                ('ygg_sale', models.IntegerField()),
            ],
            options={
                'db_table': 'yggoods',
            },
        ),
        migrations.CreateModel(
            name='YGNav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('trackid', models.IntegerField()),
            ],
            options={
                'db_table': 'ygnav',
            },
        ),
        migrations.CreateModel(
            name='YGNavDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('trackid', models.IntegerField()),
                ('yg_productid', models.IntegerField()),
            ],
            options={
                'db_table': 'ygnavdetails',
            },
        ),
        migrations.CreateModel(
            name='YGOder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_price', models.FloatField()),
                ('o_time', models.DateTimeField(auto_now=True)),
                ('o_status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ygoders',
            },
        ),
        migrations.CreateModel(
            name='YGOderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_goods_num', models.IntegerField(default=1)),
                ('o_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.YGGoods')),
                ('o_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.YGOder')),
            ],
            options={
                'db_table': 'ygoderdetail',
            },
        ),
        migrations.CreateModel(
            name='YGUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=10, unique=True)),
                ('user_pay_code', models.CharField(max_length=20, unique=True)),
                ('user_password', models.CharField(max_length=256)),
                ('user_phone', models.IntegerField(max_length=20)),
                ('user_gender', models.BooleanField()),
                ('user_name', models.CharField(max_length=20)),
                ('user_idcard', models.CharField(max_length=20)),
                ('user_img', models.CharField(max_length=30)),
                ('user_nickname', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ygusers',
            },
        ),
        migrations.CreateModel(
            name='YGWheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('trackid', models.IntegerField()),
            ],
            options={
                'db_table': 'ygwheel',
            },
        ),
        migrations.AddField(
            model_name='ygoder',
            name='o_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.YGUser'),
        ),
        migrations.AddField(
            model_name='ygcomment',
            name='yg_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.YGUser'),
        ),
        migrations.AddField(
            model_name='ygcart',
            name='c_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.YGGoods'),
        ),
        migrations.AddField(
            model_name='ygcart',
            name='c_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.YGUser'),
        ),
        migrations.AddField(
            model_name='ygaddress',
            name='yg_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.YGUser'),
        ),
    ]
