# Generated by Django 2.0.1 on 2019-06-27 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YGAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, verbose_name='用户地址')),
            ],
            options={
                'verbose_name': '用户地址',
                'verbose_name_plural': '用户地址',
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='YGCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_goods_num', models.IntegerField(default=1, verbose_name='商品数量')),
                ('c_is_select', models.BooleanField(default=True, verbose_name='是否选中')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='YGChosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=2000, verbose_name='图片')),
                ('name', models.CharField(max_length=100, verbose_name='图片名称')),
                ('trackid', models.IntegerField(verbose_name='图片ID')),
            ],
            options={
                'verbose_name': '精选推荐',
                'verbose_name_plural': '精选推荐',
                'db_table': 'chosen',
            },
        ),
        migrations.CreateModel(
            name='YGComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=500, verbose_name='用户评论')),
            ],
            options={
                'verbose_name': '用户评论',
                'verbose_name_plural': '用户评论',
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='YGEat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eat_img', models.CharField(max_length=256, verbose_name='图片')),
                ('eat_content', models.CharField(max_length=200, verbose_name='描述')),
                ('eat_time', models.CharField(max_length=50, verbose_name='时间')),
            ],
            options={
                'verbose_name': '吃喝玩乐',
                'verbose_name_plural': '吃喝玩乐',
                'db_table': 'ygeat',
            },
        ),
        migrations.CreateModel(
            name='YGGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='商品分类')),
                ('child_name', models.CharField(max_length=50, verbose_name='分类详情')),
                ('name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('detail_name', models.CharField(max_length=100, null=True, verbose_name='商品描述')),
                ('price', models.FloatField(verbose_name='商品价格')),
                ('marketprice', models.FloatField(verbose_name='市场价格')),
                ('goods_wheel_img', models.CharField(max_length=5000, verbose_name='商品图片')),
                ('pro_addr', models.CharField(max_length=200, verbose_name='生产地')),
                ('detail_img_url', models.CharField(max_length=5000, verbose_name='详情页图片')),
                ('sale', models.IntegerField(verbose_name='销量')),
                ('stock', models.IntegerField(verbose_name='库存')),
                ('category_id', models.IntegerField(verbose_name='详情id')),
                ('child_id', models.IntegerField(verbose_name='分类id')),
            ],
            options={
                'verbose_name': '商品表',
                'verbose_name_plural': '商品表',
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='YGNav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=2000, verbose_name='图片')),
                ('name', models.CharField(max_length=100, verbose_name='图片名称')),
                ('trackid', models.IntegerField(verbose_name='图片ID')),
            ],
            options={
                'verbose_name': '导航',
                'verbose_name_plural': '导航',
                'db_table': 'nav',
            },
        ),
        migrations.CreateModel(
            name='YGNavDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=2000, verbose_name='图片')),
                ('name', models.CharField(max_length=100, verbose_name='图片名称')),
                ('trackid', models.IntegerField(verbose_name='图片ID')),
                ('yg_productid', models.IntegerField()),
            ],
            options={
                'verbose_name': '导航详情',
                'verbose_name_plural': '导航详情',
                'db_table': 'details',
            },
        ),
        migrations.CreateModel(
            name='YGOderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_goods_num', models.IntegerField(default=1, verbose_name='商品数量')),
                ('o_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.YGGoods', verbose_name='商品ID')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
                'db_table': 'ygorderdetail',
            },
        ),
        migrations.CreateModel(
            name='YGOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_price', models.FloatField(verbose_name='总价格')),
                ('o_time', models.DateTimeField(auto_now=True, verbose_name='下单时间')),
                ('o_status', models.IntegerField(choices=[(0, '已下单未付款'), (1, '已下单已付款待收货'), (2, '下单后待评论')], default=(0, '已下单未付款'), verbose_name='订单状态')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'ygorders',
            },
        ),
        migrations.CreateModel(
            name='YGUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_phone', models.CharField(max_length=30, verbose_name='手机号码')),
                ('nickname', models.CharField(max_length=20, null=True, verbose_name='昵称')),
                ('gender', models.BooleanField(choices=[('0', '男'), ('1', '女')], default=0, max_length=10, verbose_name='性别')),
                ('u_auth_string', models.CharField(max_length=256, verbose_name='用户密码')),
                ('idcard', models.CharField(max_length=20, null=True, verbose_name='身份证')),
                ('img', models.ImageField(upload_to='img/%Y/%m/%d', verbose_name='用户头像')),
                ('balance', models.FloatField(default=0.0, verbose_name='账户余额')),
                ('level', models.CharField(default='普通会员', max_length=20, verbose_name='用户等级')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='YGWheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=2000, verbose_name='图片')),
                ('name', models.CharField(max_length=100, verbose_name='图片名称')),
                ('trackid', models.IntegerField(verbose_name='图片ID')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'wheel',
            },
        ),
        migrations.AddField(
            model_name='ygorder',
            name='o_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.YGUser', verbose_name='用户ID'),
        ),
        migrations.AddField(
            model_name='ygoderdetail',
            name='o_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.YGOrder', verbose_name='订单ID'),
        ),
        migrations.AddField(
            model_name='ygcomment',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.YGOrder', verbose_name='订单ID'),
        ),
        migrations.AddField(
            model_name='ygcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.YGUser', verbose_name='用户ID'),
        ),
        migrations.AddField(
            model_name='ygcart',
            name='c_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.YGGoods', verbose_name='商品ID'),
        ),
        migrations.AddField(
            model_name='ygcart',
            name='c_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.YGUser', verbose_name='用户ID'),
        ),
        migrations.AddField(
            model_name='ygaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.YGUser', verbose_name='用户ID'),
        ),
    ]
